### PR TITLE
MultiLanguage Version

### PR DESCRIPTION
**Pull request by cove9988**
1. add language setting in the extension
2. English/Chinese version. It will align with LanguageID, which will also give better LLM answers based on language selection. 
3. apply Microsoft l10n localization for command platter language changes.
4. replace all hard-coded Chinese from ts files with MultiLanguage.json

### CODE REVIEW

**Comment by 0ut0fcpu** [comment]
很赞！
我希望插件可以自动根据当前语言环境选择展示语言，不希望用户通过配置项来选择，可以做到吗？

**Comment by cove9988** [comment]
use vscode.env.language to get current language. 
There are many language sets available. please refer to https://code.visualstudio.com/docs/getstarted/locales
Adding a new language, for example japanese: 
1. add "ja" in Multilanguage.json accordingly
2. add new package.nls.ja.json.

**Comment by cove9988** [comment]
do you have a wechat group? @0ut0fcpu

**Comment by cove9988** [comment]
Don't merge this yet. I found we can also improve prompt here.

**Comment by vimBashMing** [comment]
Good job!

**Pull request merged**
